### ISSUE TITLE
Default Note component produces invalid HTML

### ISSUE THREAD

**Issue by lduktus** [bmschmidt/pandoc-svelte-components#9]
The default Note component creates a summary tag with details and then the element inside it. In most cases the Note will be at the end of a phrase, which will be inside a p tag. However the Note itself will also produce a p tag. As far as I am aware nested p tags, are invalid.

Additionally when using the w3.org validator it still warns about invalid p tags, even after removing them. It seems that summary tags will automatically close the p tag. Hence the closing p tag won't match any opening p tag.

This may be a minor issue and in my case all browsers that I used for testing display the output properly, but I think it is good to be aware about this. It connects to your comment in Elements.svelte:

> This code doesn't distinguish between inlines and blocks. I'm sure that will eventually become an issue, but for now it works.

I am currently trying to add "default" footnotes by adding a link and than passing this value with the data to the parent, pushing everything to an array and then loop over it after calling the Document component. Not sure if this will work as it currently produces a 500.

**Comment by bmschmidt** [comment]
Closing, this is addressed in 2.0
